### PR TITLE
Update leadconduit-types

### PR DESCRIPTION
**Pull request by bhicks**
Updating the `leadconduit-types` major version. This fixes an issue I ran across in where dates were parsed differently than in other leadconduit repositories.

### CODE REVIEW

**Comment by bhicks** [comment]
@alexkwolfe @cgrayson any objections to merging this change?

**Comment by cgrayson** [comment]
No objection, though I wonder if this change to use `types` 3.x changes from a month ago was delayed this long on purpose? Or forgotten?

**Comment by alexkwolfe** [comment]
LGTM. My guess is that it was forgotten.

**Comment by bhicks** [comment]
All tests pass with this change, so I leaned towards forgotten as well. Thanks!

**Pull request merged**
