### PR TITLE
Update descriptions of UTM fields so that they aren't Google specific. Bing uses the same fields.

### PR DESCRIPTION
**Pull request by alexkwolfe**

### CODE REVIEW

**Comment by cgrayson** [comment]
I don't see believe that's true, and can't find evidence to support it. Instead I see [info on UET](http://help.bingads.microsoft.com/#apex/3/en/n5012/2) (and [more here](https://www.fourfront.us/blog/how-to-track-bing-ppc-in-google-analytics)).

**Comment by alexkwolfe** [comment]
Huh. I was looking at this: http://advertise.bingads.microsoft.com/en-us/blog/28521/auto-tagging-of-destination-urls-in-bing-ads

**Comment by cgrayson** [comment]
From that post: 

> A popular request from you, our customers, has been to enable auto-tagging of destination URLs **so that you can track your paid search campaign performance in analytics programs, such as Google Analytics**.

So maybe calling them Google Analytics parameters is more accurate than Google Adwords params, but I do think they're Google's proprietary deal.

**Comment by alexkwolfe** [comment]
From your second link

>  Bing Ads UET automatically adds four types of UTM tags to the destination URLs of your ads and keywords: utm_source, utm_medium, utm_term, utm_campaign.

**Comment by alexkwolfe** [comment]
The impetus for this change is that we don't want to have keywords (and other tracking) fields, for each search provider. So if the UTM fields aren't standard across search providers, then the fields in this PR will need to be deprecated and replaced with something more general.

**Comment by cgrayson** [comment]
The _title_ of the blog post at that 2nd link is "How to Track Bing PPC in _Google Analytics_". 

AFAIK, UTM == Google, from [an acquisition 10 years ago](https://en.wikipedia.org/wiki/Urchin_%28software%29). Since Google has the vast majority of search marketshare, it's a de facto standard and has apparently been co-opted by Bing. I'm at (or beyond) my understanding of such things, but I'd guess anyone in online marketing knows of the `utm_` parameters (and knows they're for Google Analytics).

**Comment by cgrayson** [comment]
Looking at this again, I think the more descriptive text you have here is a worthwhile. Also, "Google Adwords" was never right; they're for Google Analytics. Whether you want to add mention of Google Analytics to these descriptions is up to you; either way is :+1: by me. Flip a coin to decide, if you want. :wink: 

L :chart_with_upwards_trend: T M

**Pull request merged**
